// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwchBNa9Jd1UEXI0CJgCN2Zc6Ar_ZOgI',
    appId: '1:220395204076:web:471ef979caa39ab4c264c9',
    messagingSenderId: '220395204076',
    projectId: 'livenews-a7aff',
    authDomain: 'livenews-a7aff.firebaseapp.com',
    storageBucket: 'livenews-a7aff.appspot.com',
    measurementId: 'G-H61952HCF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-epZyOR9jMABnCtMValvJSPPlx1LTsY',
    appId: '1:220395204076:android:1570cff466351155c264c9',
    messagingSenderId: '220395204076',
    projectId: 'livenews-a7aff',
    storageBucket: 'livenews-a7aff.appspot.com',
  );
}
